spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/conduitspring}
    username: ${SPRING_DATASOURCE_USERNAME:conduitspring}
    password: ${SPRING_DATASOURCE_PASSWORD:conduitspring}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # TODO: not approprate for production
    properties:
      hibernate.format_sql: true
server:
  port: ${PORT:4567}